### ISSUE TITLE
Template for issues

### ISSUE THREAD

**Issue by ninaihde** [HPI-SWA-Teaching/SWT15-Project-01#99]
- [x] acceptance test
- [x] readability
- [x] examples
- [x] use Markdown if appropriate
- [x] in case of bug: failing test or discription to reproduce bug
- [x] concrete method names and calling objects
- [x] label usage for categorization
- [x] reminder to add issue to the project
- [x] checkboxes for subtasks or acceptance criteria
- [x] author estimates issue
- [x] try to write a short issue

**Comment by richardebeling** [comment]
So, I looked around to find templates other projects use, and there is basically one problem: We use Issues for feature requests as well as bug reports. Big open source software that has templates usually has two trackers, one for each. Then, templates make more sense since you'd write a bug report differently than a feature request. But well. I'll try to format a template and post it below, we can then discuss it.

We should remember to also use tags / labels

**Comment by richardebeling** [comment]
### Subject
(A short description of what this issue is about. This shouldn't be more than two lines.)

### Details
(If this is a feature request, explain why it should be added. Specific use-cases are best.
For bug reports, please provide as much relevant info as possible.)

### Tasks / Acceptance Criteria
- [ ] (List of steps that need to be completed in order for this issue to be complete)

### Test Code / Example Code
```smalltalk
(For bugs: A failing test showing the issue.
For feature requests: Tests you would like this feature to pass or code that demonstrates the feature)
```


---
# (Include this in bug reports)
### Version
What version of squeak is affected? (5.0, 5.1, trunk, SWT image): 
Which version of RatPack is affected? (commit hash, branch name): 

### Steps to Reproduce
- (List of steps required to see the bug)

### Expected Behaviour
(What did you expect to happen?)

### Actual Behaviour
(What happened?)

### Output
(Are there error messages? If yes, which? Does a debugger window open? If yes, what does it show?)

---
# (Include this in all issues)

### Efford estimation
(Put your estimation here)

### I'm not a dummy, so I have thought about all these points and removed them if I'm sure they are fulfilled
- I have searched for similar issues. I referenced all of these. I'm sure this is not a duplicate.
- I have reread my whole post. It's readable and easily understandable. Also, it's as short as possible
- I have used markdown formatting where appropriate
- When I'm referring code, I have made clear which piece of code I mean (class and method name).
- I have assigned this issue to the SWT Project
- I have labelled this issue

**Comment by richardebeling** [comment]
Now this is very long, it's even too big for one screen.

@Nina510 @essal0815 @skydivin4ng3l @jakobmache what do you think?

**Comment by essal0815** [comment]
I think it is a good thing to have and also shown as Default. I think its not realistic to fill out each thing for one issue, but I like to have this as Good Practise where I can check whether I forget something important. So I think we shall use this as a template or inspiration but not forcing us to use it, more as help.
So I'm not sure how to handle, template or wiki entry. I would suggest, we use the template feature, so you don't always have to switch between tabs and can edit immediately and remove/skip the points which might not so relevant.

**Comment by richardebeling** [comment]
Alright, stuff I don't like:
- For issues, Github tracks their "progress" by the selected checkboxes. We now have two different types of checkboxes in an issue. Some are for the progress in working on this issue, some are for the progress in writing the issue. Github thus mixes them up. If you specify one acceptance criterium and select all the "I'm not a dummy" checkboxes, Github will show the issue at 6/7 progress. I don't like it.
- Issues look the same. If you have multiple tabs open, all on issues, all on the top of the page. Usually you can very quickly see whether a tab you've just selected is the tab you really want since every issue has it's own overall look (short, long, example, check lists, ...). With the template, all issues look the same (obviously). If I now have 5 tabs open with 5 different issues, it takes much more time to find the one issue I was after.
Edit: To be fair, if I looked at the caption instead of the content, this would be irrelevant. I should probably just change my habit there.

**Comment by ninaihde** [comment]
Regarding the checkbox problem: how about having the dummy bullet points just as a reminder (kind of comment) in the template but deleting them before creating the new issue?
All in all, the template is a good orientation from which you can take the parts that matter for your issue.

It should became a wiki entry to find it more quickly - what do you think?

**Comment by richardebeling** [comment]
If we decide to use it, it should become our issue template on github. No need for a wiki page. I like the idea of using bullet points instead of checkboxes. Will adapt.

Fair enough, I think its good enough now to actually make this our template. If all of you agree, I'd ask Tom to apply this next wednesday

**Comment by Nina510** [comment]
Yes, I agree with it.

**Comment by ninaihde** [comment]
Yes, I agree with that.

**Comment by essal0815** [comment]
I agree as well with the bulletpoints (or deleting them after doing it).

I don’t see a solution yet for the similar appearance problem.

I understand the problem, but I think die uniform issues we always will also uniform the appearance.

My question @He3lixxx is:
What is your use case of having 5 issues open the same time, just to make me understand your problem better.
Are the issues referencing each other that much or do you have that many open due estimation or you work on all the stuff the same time ;)

**Comment by richardebeling** [comment]
I'm just a many-tabs-guy, open tabs means stuff I want to look at or work on. So, when I have 5 github emails for 5 issues in my inbox, I open all pages in a browser and work in the browser from there on.

We had some duplication / interconnection between issues lately, but there was nothing really wrong I think.
